version: '1.0'

services:
  db:
    image: postgres
    container_name: txn-svc-postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  api:
    container_name: txn-svc-api
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
