basePath: /
definitions:
  account.CreateAccountRequest:
    properties:
      document_number:
        type: string
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.Response:
    properties:
      data: {}
      errors:
        $ref: '#/definitions/handler.Error'
    type: object
  transaction.CreateTransactionRequest:
    properties:
      account_id:
        type: string
      amount:
        type: number
      operation_type_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API Doc for Transaction Service.
  title: Transaction Service APIs
  version: 1.0.0
paths:
  /v1/accounts:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Create a new account
      tags:
      - Accounts
  /v1/accounts/{account_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: account id
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Get account by id
      tags:
      - Accounts
  /v1/transactions:
    post:
      consumes:
      - application/json
      parameters:
      - description: Transaction object
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/transaction.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Create transaction
      tags:
      - Transactions
swagger: "2.0"
