name: Schedule an Airflow DAG

on:
  workflow_dispatch:
    inputs:
      campaignId:
        description: 'Campaign ID'
        required: true
      campaignName:
        description: 'Campaign Name'
        required: true
      dagId:
        description: 'Dag ID'
        required: true
      schedule:
        description: 'Schedule ex: 2024-10-12 12:21:12'
        required: true
      scheduleType:
        description: 'Type of schedule (one-time / recurring)'
        required: true

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Inputs
        run: |
          echo "Campaign ID: ${{ github.event.inputs.campaignId }}"
          echo "Campaign Name: ${{ github.event.inputs.campaignName }}"
          echo "Schedule: ${{ github.event.inputs.schedule }}"
          echo "Dag ID: ${{ github.event.inputs.dagId }}"

  generate-dag:
    needs: validate-inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
#
#      - name: Install dependencies
#        run: |
#          pip install pytz  # Install any required dependencies

      - name: Run DAG generation script
        run: |
          python /home/runner/work/transaction-service/transaction-service/xyz/generate_dag.py "${{ github.event.inputs.dag_id }} ${{ github.event.inputs.campaign_id }}" "${{ github.event.inputs.schedule }}" "${{ github.event.inputs.schedule_type }}"

      - name: Commit and Push the DAG file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b "new_test"
          git add airflow/dags/${{ github.event.inputs.dagId }}.py
          git commit -m "Added Dag ID: ${{ github.event.inputs.dagId }}"
          git push
